### ISSUE TITLE
Dealing with large files

### ISSUE THREAD

**Issue by erikvullings** [DRIVER-EU/test-bed#22]
When the client (that uses an adapter) wants to produce a very large message, e.g. a detailed map of the flooding, we should not send it over Kafka. Instead, it would be better to store it somewhere, and create and publish a derived message, indicating where the source is stored.

**Comment by PHameete** [comment]
I suggest we use a wetransfer-like approach on an FTP server. If an adapter wishes to transmit a large file: upload it to an automatically generated 'obfuscated' path on the FTP server. Once the upload is completed send out the message on Kafka with the path where the file can be retrieved and its metadata. 

I'll see if I can set up an FTP server with anonymous read/write access but that forbids overwriting existing files.

**Comment by PHameete** [comment]
We've added nextcloud to the docker environment.
