### ISSUE TITLE
Find a solution how to deal with config files

### ISSUE THREAD

**Issue by erikvullings** [DRIVER-EU/test-bed#23]
Many applications, like csCOP, admin tool, mbtiles etc. need a config folder with extra information. How are we going to manage them?

**Comment by PHameete** [comment]
large time service added in local test bed composition on development branch.

@erikvullings please try this out.

**Comment by PHameete** [comment]
For reference, llarge file service repository can be found here:

https://github.com/driver-eu/large-file-service
