### ISSUE TITLE
Docker - Authzforce Kafka Extension via Docker Volume Container

### ISSUE THREAD

**Issue by PHameete** [DRIVER-EU/test-bed#29]
Currently, we use an .sh script that has to be run to retrieve a jar deliverable from Github. That jar is then volume mounted from the host into the Kafka Broker.

Can we change this to release the Authzforce jar as a Docker Image, and then share the .jar via a volume. This volume can then be mounted by the Kafka broker.

This should remove the need for the .sh script which is yet another user action required to start the test bed, and another place where the version number must be managed.

**Comment by cdanger** [comment]
Yes, good idea. Go ahead :-)

**Comment by cdanger** [comment]
In the end, I did it myself.

**Comment by PHameete** [comment]
Perfect Cyril, thank you :-)
